Revision: 3d7d2af4c6502b771b032ee9bf3ab30e78f9c60d
Base-for-patch-set: 2
File: runtime/check_jni.cc

1068:6-1072:74
Thu Mar 05 11:32:19 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: d22fde6e_27e0ba98
Bytes: 158
We should still be able to dump the location where the exception was thrown from. This must be saved in the exception object when we computed its stack trace.

1068:6-1072:74
Thu Mar 05 11:46:30 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: d22fde6e_27e0ba98
UUID: 929c86d9_d346ac2a
Bytes: 142
This is a "nice to have message" but not so much a requirement. If one wants this level of information, he should probably open up a debugger.

File: runtime/runtime.cc

309:6-313:31
Thu Mar 05 11:32:19 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 929c86d9_738898ed
Bytes: 43
We should dump the throw location here too.

309:6-313:31
Thu Mar 05 11:46:30 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 929c86d9_738898ed
UUID: d22fde6e_87b88662
Bytes: 106
Same reply as before: kind of a best effort message, and the developer should probably open up a debugger.

