Revision: 48c1ce0ca0fae3cad33a19efd39ce434b530fd83
Patch-set: 1
File: runtime/class_linker.cc

4317:1-4329:5
Thu Oct 09 15:33:55 2014 +0000
Author: Ian Rogers <1010118@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: f0820c18_99106771
Bytes: 165
This case is weird, we're marking a class as erroneous because the thread waiting was interrupted? We should remove or fix the comment to say what's really going on.

4317:1-4329:5
Thu Oct 09 17:35:59 2014 +0000
Author: Brian Carlstrom <1003723@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: f0820c18_99106771
UUID: 30974456_d245640d
Bytes: 274
Your WaitIgnoringInterrupts obsoleted this comment a bit. That seems to be masking the interruptShouldThrow=false. But even before, this seemed to be dealing with a very odd case, since it seems to be saying WTF, how did we get an exception if we said not to be interrupted.

