Revision: e19af078c119543ea8c8d775327d69e85db55ef2
Patch-set: 1
File: runtime/instrumentation.cc

741:6-741:8
Tue Apr 01 15:17:00 2014 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 79b43fb0_8b99b1ad
Bytes: 78
Is ++it guaranteed to work safely in the presence of concurrent modifications?

741:6-741:8
Tue Apr 01 15:25:30 2014 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 79b43fb0_8b99b1ad
UUID: 59b93ba9_2a52ff2c
Bytes: 260
Good point. I think it works in my case because the debugger is the only listener so it will point to end(). I guess that's not working if it points to an element that gonna be removed. Making a copy of the list and loop over this copy may be safer in the end.

753:4-753:29
Tue Apr 01 14:52:44 2014 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 59b93ba9_ea11476e
Bytes: 143
We should use a SIRT parameter for the exception_object so we ensure exception is still reachable while we clear it from thread. Am I correct ?

