Revision: e8d1e0d29a93610b5d8d23be3fbbfc0753f10772
Patch-set: 2
File: runtime/interpreter/unstarted_runtime.cc

267:47-267:90
Thu Mar 12 10:00:37 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 01bbe6f2_b872399c
Bytes: 8
Why not?

307:4-307:26
Thu Mar 12 10:54:16 2015 +0000
Author: Sebastien Hertz <1029223@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 01bbe6f2_f8cb111f
Bytes: 96
Shouldn't we throw a NullPointerException here? What if the caller may handle it with try/catch.

323:4-323:57
Thu Mar 12 10:00:37 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 017da6ec_08efc7b9
Bytes: 61
Really? Isn't it OK if there is a try/catch on the user side?

336:0-347:98
Thu Mar 12 10:00:37 2015 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 017da6ec_28f48b89
Bytes: 5
ditto

