Got an NPE: second throw
java.lang.NullPointerException: second throw
	at Main.catchAndRethrow(Main.java:62)
	at Main.exceptions_007(Main.java:45)
	at Main.main(Main.java:53)
Caused by: java.lang.NullPointerException: first throw
	at Main.throwNullPointerException(Main.java:69)
	at Main.catchAndRethrow(Main.java:59)
	... 2 more
Static Init
BadError: This is bad by convention: BadInit
BadError: This is bad by convention: BadInit
